# 連立方程式の解法

## Sympy を使う方法

In [1]:
import sympy as sp

In [2]:
sp.init_printing()

In [5]:
x1, x2, x3, x4 = sp.symbols('x1 x2 x3 x4')

In [6]:
sp.solve([3 * x1 + 2 * x2 + 7 * x3 + x4 - 8,
         x1 + 5 * x2 + x3 - x4 - 5,
         4 * x1 + x2 + 3 * x3  - 2 * x4 - 7,
         x1 + 6 * x2 + 4 * x3 + 3 * x4 - 13], [x1, x2, x3, x4])

In [7]:
x1, x2, x3, x4, x5 = sp.symbols('x1 x2 x3 x4 x5')

In [8]:
sp.solve([x1 + x2 + x3 + x4 + 5 * x5 - 14,
         3 * x1 + 2 * x2 + 10 * x3 + 4 * x5 - 12,
         15 * x1 + 2 * x2 + 3 * x3 + 4 * x4 + 5 * x5 - 20,
         x1 + 10 * x2 + x3 + 3 * x4 - 15,
         3 * x2 + 5 * x3 + 15 * x4 + x5 - 10], [x1, x2, x3, x4, x5])

In [9]:
sp.solve([x1 + x2 + x3 - 20, 
       x1 * x2 * x3 + 234, 
       2 * x1 + 5 * x2 -  x3 - 85], [x1, x2, x3])

In [10]:
a, b, c, d, e, f = sp.symbols('a b c d e f')
sp.solve([a * x1 + b * x2 + c * x3 + d * x4 + e * x5 + f], [x1])

## Numpy.ligalg や Scipy.linalg を使う方法

In [50]:
import numpy as np

A = np.array([
    [3, 2, 7, 1],
    [1, 5, 1, -1],
    [4, 1, 3, -2],
    [1, 6, 4, 3]
])
b = np.array([8, 5, 7, 13])

### Numpy.linalg を使う方法 (1)

In [47]:
x = np.linalg.solve(A, b)
print(x)

[ 3.5  1.  -1.   2.5]


### Numpy.linalg を使う方法 (2)

In [48]:
Ainv = np.linalg.inv(A)         # A の逆行列を計算
x = np.dot(Ainv, b)             # A の逆行列と b の内積
print(x)

[ 3.5  1.  -1.   2.5]


### Scipy を使う方法

In [49]:
from scipy import linalg
LU = linalg.lu_factor(A)
x = linalg.lu_solve(LU, b)
print(x)

[ 3.5  1.  -1.   2.5]


# 線形重回帰分析と連立方程式

線形重回帰における回帰係数は、実測値と予測値ができるだけ小さくなるように求めます。具体的には、残差平方和が最小となるようにします。たとえば

y = a<sub>0</sub> + a<sub>1</sub> * x<sub>1</sub> + a<sub>2</sub> *  x<sub>2</sub>

の回帰係数 a<sub>1</sub>, a<sub>2</sub> は、次の連立方程式で求めます。

* S<sub>11</sub> * a<sub>1</sub> + S<sub>12</sub> * a<sub>2</sub> = S<sub>y1</sub>
* S<sub>21</sub> * a<sub>1</sub> + S<sub>22</sub> * a<sub>2</sub> = S<sub>y2</sub>

ここで、S<sub>ij</sub> は、i の偏差（平均との差）と j の偏差との積和です。 

回帰係数が求まれば、a<sub>0</sub> は

* a<sub>0</sub> = average( y ) - a<sub>1</sub> * average( x<sub>1</sub> ) - a<sub>2</sub> * average( x<sub>2</sub> )

で求められます。